// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class MedicalCareTabTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void medicalCareTab() {
    driver.Navigate().GoToUrl("https://www.amazon.com/ref=nav_logo");
    vars["title"] = driver.Title;
    if ((Boolean) js.ExecuteScript("return (arguments[0]!=\'Amazon\')", vars["title"])) {
      driver.Navigate().GoToUrl("https://www.amazon.jobs/en/a");
    }
    driver.Manage().Window.Size = new System.Drawing.Size(783, 824);
    js.ExecuteScript("window.scrollTo(0,3988.800048828125)");
    driver.FindElement(By.LinkText("Careers")).Click();
    driver.Close();
  }
}
