// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Linq.Expressions;
using System.CodeDom;
using System.Data;
using System.Reflection;
using System.Security.Cryptography.X509Certificates;
[TestFixture]
public class AmazonTest {
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp() {
        driver = new ChromeDriver();
        /*options.BrowserExecutableLocation = (C:\\Program Files\\)*/
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown() {
        driver.Quit();
    }
    /* new code */

    [Test]
    public static void newTest()
    {

        void repeat()
        {
            IWebDriver driver = new ChromeDriver();

            /* driver . something is what the code can touch */
            driver.Navigate().GoToUrl("https://amazon.com");

            driver.ToString();


            Assert.That(driver.Title, Is.EqualTo("Amazon.com"));

            for (int i = 0; i < 2; i++)
            {
                driver.GetHashCode();
                driver.GetType();
            }

            if (driver.Title == "Amazon.com")
            {
                Console.Write("This is an amazon website");
            }
            else if (driver.Title == "Amazon Labs.com")
            {
                Console.Write(driver.Title);
                Console.WriteLine("This is another amazon site");
            }
            else
            {
                Console.WriteLine("This is not an amazon site.. now quitting");
                driver.Quit();
            }
        }

        repeat();
        
    }

    [Test]
    public static void clickOnItem()
    {
        IWebDriver driver = new ChromeDriver();

        driver.Navigate().GoToUrl("https://Amazon.com");

        driver.ToString();

        Assert.That(driver.Equals("ELEMENT"), Is.EqualTo(true));
       

        Assert.That(driver.Equals("https://amazon.com"), Is.True);

        Assert.That(driver.Url.Equals("https://amazon.com"), Is.True);

        driver.Url = "https://amazon.com";

        String title = driver.Title; 

        int TitleLength = driver.Title.Length;

        Console.WriteLine("This title of this age is: ", title," and the length is: ", TitleLength);

        string PageUrl = driver.Url;

        int PageSourceLength = driver.PageSource.Length;

        driver.FindElement(By.XPath(".//*[@id='tabs-1']/div/p/a")).Click();

        driver.Quit();

    }

    [Test]
public static void clickOnItem2()
    {
        IWebDriver driver = new ChromeDriver();
        driver.FindElements(By.Id("name"));
        int titleLength = driver.Title.Length + 1;
        Console.WriteLine(titleLength);

        string pageUrl = driver.Url;
    }

    /* this is where it was */

    [Test]

    public static void clickOnTitle()
    {
        IWebDriver driver = new ChromeDriver();
        driver.FindElement(By.XPath("string"));

        driver.FindElement(By.CssSelector("title")).Click();

        int titleLength = driver.Title.Length;
        Console.WriteLine(titleLength + 1);

        string pageUrl = driver.Url;

        Console.WriteLine("this is the URL of the profile: ", pageUrl);

        driver.Navigate().GoToUrl(pageUrl);

        driver.SwitchTo().Window(pageUrl);

        driver.SwitchTo().Window(pageUrl); driver.SwitchTo().Window(pageUrl);

        driver.SwitchTo().Window(pageUrl);

        Console.WriteLine(driver.ToString());
        Console.WriteLine(pageUrl);

        driver.FindElement(By.XPath(""));



        driver.Quit();
    }
}
